blank_issues_enabled: true

contact_links:
  - name: â“ Ask a Question / General Discussion
    url: https://discordapp.com/channels/1346487271225954384/1358845326580252713
    about: Please ask usage questions and discuss ideas on our Discord channel.